### ISSUE TITLE
Update copyright year to 2023

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1673]
### Desired Behaviour

Update the copyright year in all source files (is it anywhere else?).

Updating `.licenserc.json` and running `AddLicensesToFiles.py` script should work.

Also probably a good time to move the Add and Check license scripts into the scripts directory.

**Comment by JackEAllen** [comment]
I have explored moving `AddLicensesToFiles.py` and `CheckLicensesInFiles.py` into `scripts/` subdirectory. I can't see any immediately easy way to do this due to scoping problems I have experienced attempting to move them when updating the pre-commit to look in the scripts directory (`/home/<user>/.cache/pre-commit/repo0hyhni6f/py_env-python3.9/bin/python: No module named scripts/CheckLicensesInFiles`).

**Comment by JackEAllen** [comment]
> I have explored moving `AddLicensesToFiles.py` and `CheckLicensesInFiles.py` into `scripts/` subdirectory. I can't see any immediately easy way to do this due to scoping problems I have experienced attempting to move them when updating the pre-commit to look in the scripts directory (`/home/<user>/.cache/pre-commit/repo0hyhni6f/py_env-python3.9/bin/python: No module named scripts/CheckLicensesInFiles`).

I was able to access and execute `CheckLicensesInFiles.py` when placed in the `scripts` sub-directory, from the `.pre-commit-config.yaml`, by using the following:
```
-   repo: local
    hooks:
    -   id: check-licenses
        name: Check Licenses
        description: Checks that all files have correct copyright licenses
        entry: bash -c "python -m script/CheckLicensesInFiles.py"
        pass_filenames: false
        language: python
        types: [python]
```
However, because this is running `CheckLicensesInFiles.py` `sys.argv[1:]` [line 53] from the interpreter, which is not any module nor file, sys.argv will only produce an empty string and therefore will pass even if it should fail if a copyright docstring has not been updated or is missing from a given file.
