### ISSUE TITLE
Move Copyright Scripts From Base Directory into Scripts Sub-Directory

### ISSUE THREAD

**Issue by JackEAllen** [mantidproject/mantidimaging#1677]
### Desired Behaviour

As a developer, I would like to move the following copyright scripts into the `/scripts/` sub-directory and modify the current implementation of `sys.argv[1:]` `[line 53]` within `CheckLicensesInFiles.py` and `.pre-commit-config.yaml` accordingly to clean up the codebase and retain current behaviour when used in pre-commit checks. 
* `CheckLicensesInFiles.py`
* `AddLicensesToFiles.py`

Current behaviour of `CheckLicensesInFiles.py` can be tested by running the pre-commit checks (`pre-commit run`)and removing copyright docstrings form scripts within the codebase. 

Current behaviour of `AddLicensesToFiles.py` can be tested by changing the copyright docstring in `.licenserc.json` and running `AddLicensesToFiles.py` (`python AddLicensesToFiles.py), then checking docstrings have been updated correctly.

**NOTE that any changes to the year of the copyright when testing do not currently apply to `docs/conf.py` `[line 70]` when executing `AddLicensesToFiles.py` **

### Current Behaviour

Moving the above scripts into `/scripts/` will cause `.pre-commit-config.yaml` to fail as the scope of the pre-commit does not currently extend into subdirectories. 

`.pre-commit-config.yaml` will need to be updated to allow this using an implementation similar to this:
```yaml
-   repo: local
    hooks:
    -   id: check-licenses
        name: Check Licenses
        description: Checks that all files have correct copyright licenses
        entry: bash -c "python -m script/CheckLicensesInFiles.py"
        pass_filenames: false
        language: python
        types: [python]
```
As the above implementation uses bash in the entry point, when `CheckLicensesInFiles.py` executes `sys.argv[1:]` `[line 53]` to return a list of filenames in the current relative directory,  `sys.argv[1:]` will return an empty string and cause `CheckLicensesInFiles.py` to pass even if a copyright docstring is missing or not up to date with .licenserc.json. This behaviour occurs because the script will be running in the interpreter which is not a module no file.

The current implementation of `sys.argv[1:]` `[line 53]` within `CheckLicensesInFiles.py` will need to be changed to use a file walker or other implementation to retrieve a list of filenames if using a similar approach to that suggested above for the pre-commit changes.
