### ISSUE TITLE
Resolve merge queue and path filtering

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#2505]
### Summary

We want to use the Github Merge Queue, to test PRs on main before merging.
This requires having "Require status checks to pass before merging" enabled in the branch protection rules, and a list of "Status checks that are required"

![Image](https://github.com/user-attachments/assets/e678b47e-305e-451a-a909-c3bfa55aab77)

These rules also prevent a PR merging untill those workflows have run.

We also use filtering rules to avoid having to run all the tests if there are no code changes:

```yaml
on:
  push:
    branches:
    - 'main'
    - 'release-*'
  pull_request:
    paths:
      - '**'
      - '!docs/**'
  release:
  merge_group:
```
These mean that those workflows don't run, and so never reach the success state

![Image](https://github.com/user-attachments/assets/a6e3b9d6-5b69-41ad-a3e2-1570b83fb325)
